name: we_chat
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  lottie: ^3.1.2
  image_picker: ^0.8.7+3 # Updated version supporting null safety
  get: ^4.6.5 # Make sure GetX is the correct version with null safety
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  firebase_storage: ^12.3.1
  firebase_cloud_firestore: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Add assets as needed
  # assets:
  #   - assets/images/app_logo.png
  #   - assets/images/profile.png
  #   - assets/images/background.jpg

  # Add custom fonts as needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
